### ISSUE TITLE
mode = motif not working as intended 

### ISSUE THREAD

**Issue by jalan01** [lehner-lab/canya#1]
Hi, 
Many thanks for the nice tool. It works flawlessly except for one small glitch. 

The flag "--mode motif” does not output residue-wise cluster scores. It simply outputs a .out file as if the flag was not present. 
I am running Ubuntu 22.04.5 LTS

> canya --input ../own.fasta --output own.out --mode motif --act max

2024-12-27 21:12:11.407024: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-12-27 21:12:11.407039: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-27 21:12:11.878740: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-12-27 21:12:11.878758: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (munchli): /proc/driver/nvidia/version does not exist
2024-12-27 21:12:11.878928: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
loaded model!
Detected FASTA input (starts with '>')
Read input
2024-12-27 21:12:12.308743: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Finished 100% (19/19) of sequences

**Comment by mj-thompson** [comment]
Hi there. Thanks for your interest in the tool!

Ultimately it was something we decided to remove in favor of developing a few other options--
`ensemble` which will allow calculating scores over 10 trained model instances as well as the standard deviation across trained model instances (i.e. epistemic uncertainty)
`summarize` which, when set to 'no,' will retain the CANYA score at every calculated window, rather than take the minimum across the sequence. We now train CANYA using just the length-20 sequences from the assay, so the window size is much smaller than when including Sup35N. The code has been updated, and the preprint will be soon.

If this motif mode turns out to be something of interest, we can implement it.

Best,
Mike

**Comment by jalan01** [comment]
Dear Mike, 

Many thanks for the clarification and update. I noticed that the new version appears to give more false positives than the earlier one with WaltzDB database at score cutoff of 0.1. For example, the older version identified 430 of 515 sequences as positive and 528 of 901 as negative hits. The new version identified 479 of 515 sequences as positive 363 of 901 as negative hits. Increasing the score cut-off to 0.15 dramatically lowers positive hits (224 of 515) while doing really well with negative hits (829 of 901). Really appreciate any suggestions on which cutoff would be more appropriate. 

Further, we are trying to understand domain-wise amyloidogenic propensity across orthologues. It would be really nice to have residue-specific scores as performed by the motif flag for this purpose. 

regards, 
Abhishek

**Comment by mj-thompson** [comment]
Hmm, so I'm reluctant to suggest a threshold for cut-off---this can potentially be non-trivial since the case-control balance in our dataset is different than that of WaltzDB---and instead might recommend something rank-based, or more continuous like area under ROC or PR curves.

If you really would like to use a threshold, maybe it's better to increase the granularity until you find a TPR/TNR that you're content with, by changing the threshold from 0.10 to 0.15 in steps of, say, 0.01 or 0.001. 

Finally, a useful bit of information for you could also be the epistemic error now included from running the package in ensemble mode. Perhaps in the mis-classified sequences, you'll notice a relationship with this error, and can use some function of the score & error (imagine something analogous to a Z-score) to help you find a threshold.

I'm going to close the issue since it no longer relates to options in the package, but if you want to continue the discussion, please feel free to open another issue or contact me via email.

Thanks,
Mike
